application:
    mode: debug #gin的启动模式， debug or release or test
    #    serverip: cms_api.greensci.online
    #    url: http://cms_api.greensci.online/
    server_ip: localhost
    url: http://localhost:15907/
    port: 15907
log:
    path: logs # 日志文件目录
    filePrefix: gin # 日志文件前缀
    fileFormat: 2006-01-02 # 日志文件名格式
    level: info # 最低记录级别
    outFormat: json # json/console
    lumberJack: # 日志文件切割和压缩
        maxSize: 1 # 单文件最大容量(单位MB)
        maxBackups: 3 # 保留旧文件的最大数量
        maxAge: 30 # 旧文件最多保存几天
        compress: false #是否压缩/归档旧文件